# docker-compose.yml

services:
  mongodb:
    image: mongo:noble
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    networks:
      - mongo-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo-data:

networks:
  mongo-network:
    external: false
